services:
  postgres:
    container_name: postgres1
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: test123
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "7878:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin1
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "4040:80"
    networks:
      - postgres
    restart: unless-stopped
    
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: